/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import { Contract, Interface, type ContractRunner } from "ethers";
import type {
  IUniswapV2Migrator,
  IUniswapV2MigratorInterface,
} from "../../../../contracts/uniswap-v2-periphery/interfaces/IUniswapV2Migrator";

const _abi = [
  {
    inputs: [
      {
        internalType: "address",
        name: "token",
        type: "address",
      },
      {
        internalType: "uint256",
        name: "amountTokenMin",
        type: "uint256",
      },
      {
        internalType: "uint256",
        name: "amountETHMin",
        type: "uint256",
      },
      {
        internalType: "address",
        name: "to",
        type: "address",
      },
      {
        internalType: "uint256",
        name: "deadline",
        type: "uint256",
      },
    ],
    name: "migrate",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
] as const;

export class IUniswapV2Migrator__factory {
  static readonly abi = _abi;
  static createInterface(): IUniswapV2MigratorInterface {
    return new Interface(_abi) as IUniswapV2MigratorInterface;
  }
  static connect(
    address: string,
    runner?: ContractRunner | null
  ): IUniswapV2Migrator {
    return new Contract(address, _abi, runner) as unknown as IUniswapV2Migrator;
  }
}
