/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import { Contract, Interface, type ContractRunner } from "ethers";
import type {
  IMigrator,
  IMigratorInterface,
} from "../../../../contracts/uniswap-v2-locker/UniswapV2Locker.sol/IMigrator";

const _abi = [
  {
    inputs: [
      {
        internalType: "address",
        name: "lpToken",
        type: "address",
      },
      {
        internalType: "uint256",
        name: "amount",
        type: "uint256",
      },
      {
        internalType: "uint256",
        name: "unlockDate",
        type: "uint256",
      },
      {
        internalType: "address",
        name: "owner",
        type: "address",
      },
    ],
    name: "migrate",
    outputs: [
      {
        internalType: "bool",
        name: "",
        type: "bool",
      },
    ],
    stateMutability: "nonpayable",
    type: "function",
  },
] as const;

export class IMigrator__factory {
  static readonly abi = _abi;
  static createInterface(): IMigratorInterface {
    return new Interface(_abi) as IMigratorInterface;
  }
  static connect(address: string, runner?: ContractRunner | null): IMigrator {
    return new Contract(address, _abi, runner) as unknown as IMigrator;
  }
}
