/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import { Contract, Interface, type ContractRunner } from "ethers";
import type {
  IUniFactory,
  IUniFactoryInterface,
} from "../../../../contracts/uniswap-v2-locker/UniswapV2Locker.sol/IUniFactory";

const _abi = [
  {
    inputs: [
      {
        internalType: "address",
        name: "tokenA",
        type: "address",
      },
      {
        internalType: "address",
        name: "tokenB",
        type: "address",
      },
    ],
    name: "getPair",
    outputs: [
      {
        internalType: "address",
        name: "",
        type: "address",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
] as const;

export class IUniFactory__factory {
  static readonly abi = _abi;
  static createInterface(): IUniFactoryInterface {
    return new Interface(_abi) as IUniFactoryInterface;
  }
  static connect(address: string, runner?: ContractRunner | null): IUniFactory {
    return new Contract(address, _abi, runner) as unknown as IUniFactory;
  }
}
