FROM 475911326710.dkr.ecr.ap-northeast-1.amazonaws.com/node:20.11.1-slim as build

WORKDIR /zklink-merge-token-web

ADD . /zklink-merge-token-web

RUN npm install -g pnpm && pnpm install && pnpm build:prod

FROM 475911326710.dkr.ecr.ap-northeast-1.amazonaws.com/nginx:alpine3.18

RUN mkdir /build

COPY --from=build /zklink-merge-token-web/dist /dist

CMD ["/bin/sh", "-c", "nginx -g 'daemon off;'"]