/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumberish,
  BytesLike,
  FunctionFragment,
  Result,
  Interface,
  AddressLike,
  ContractRunner,
  ContractMethod,
  Listener,
} from "ethers";
import type {
  TypedContractEvent,
  TypedDeferredTopicFilter,
  TypedEventLog,
  TypedListener,
  TypedContractMethod,
} from "../../../common";

export interface ExampleComputeLiquidityValueInterface extends Interface {
  getFunction(
    nameOrSignature:
      | "factory"
      | "getGasCostOfGetLiquidityValueAfterArbitrageToPrice"
      | "getLiquidityValue"
      | "getLiquidityValueAfterArbitrageToPrice"
      | "getReservesAfterArbitrage"
  ): FunctionFragment;

  encodeFunctionData(functionFragment: "factory", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "getGasCostOfGetLiquidityValueAfterArbitrageToPrice",
    values: [AddressLike, AddressLike, BigNumberish, BigNumberish, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "getLiquidityValue",
    values: [AddressLike, AddressLike, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "getLiquidityValueAfterArbitrageToPrice",
    values: [AddressLike, AddressLike, BigNumberish, BigNumberish, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "getReservesAfterArbitrage",
    values: [AddressLike, AddressLike, BigNumberish, BigNumberish]
  ): string;

  decodeFunctionResult(functionFragment: "factory", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "getGasCostOfGetLiquidityValueAfterArbitrageToPrice",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getLiquidityValue",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getLiquidityValueAfterArbitrageToPrice",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getReservesAfterArbitrage",
    data: BytesLike
  ): Result;
}

export interface ExampleComputeLiquidityValue extends BaseContract {
  connect(runner?: ContractRunner | null): ExampleComputeLiquidityValue;
  waitForDeployment(): Promise<this>;

  interface: ExampleComputeLiquidityValueInterface;

  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  on<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  once<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  once<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>;
  removeAllListeners<TCEvent extends TypedContractEvent>(
    event?: TCEvent
  ): Promise<this>;

  factory: TypedContractMethod<[], [string], "view">;

  getGasCostOfGetLiquidityValueAfterArbitrageToPrice: TypedContractMethod<
    [
      tokenA: AddressLike,
      tokenB: AddressLike,
      truePriceTokenA: BigNumberish,
      truePriceTokenB: BigNumberish,
      liquidityAmount: BigNumberish
    ],
    [bigint],
    "view"
  >;

  getLiquidityValue: TypedContractMethod<
    [tokenA: AddressLike, tokenB: AddressLike, liquidityAmount: BigNumberish],
    [[bigint, bigint] & { tokenAAmount: bigint; tokenBAmount: bigint }],
    "view"
  >;

  getLiquidityValueAfterArbitrageToPrice: TypedContractMethod<
    [
      tokenA: AddressLike,
      tokenB: AddressLike,
      truePriceTokenA: BigNumberish,
      truePriceTokenB: BigNumberish,
      liquidityAmount: BigNumberish
    ],
    [[bigint, bigint] & { tokenAAmount: bigint; tokenBAmount: bigint }],
    "view"
  >;

  getReservesAfterArbitrage: TypedContractMethod<
    [
      tokenA: AddressLike,
      tokenB: AddressLike,
      truePriceTokenA: BigNumberish,
      truePriceTokenB: BigNumberish
    ],
    [[bigint, bigint] & { reserveA: bigint; reserveB: bigint }],
    "view"
  >;

  getFunction<T extends ContractMethod = ContractMethod>(
    key: string | FunctionFragment
  ): T;

  getFunction(
    nameOrSignature: "factory"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "getGasCostOfGetLiquidityValueAfterArbitrageToPrice"
  ): TypedContractMethod<
    [
      tokenA: AddressLike,
      tokenB: AddressLike,
      truePriceTokenA: BigNumberish,
      truePriceTokenB: BigNumberish,
      liquidityAmount: BigNumberish
    ],
    [bigint],
    "view"
  >;
  getFunction(
    nameOrSignature: "getLiquidityValue"
  ): TypedContractMethod<
    [tokenA: AddressLike, tokenB: AddressLike, liquidityAmount: BigNumberish],
    [[bigint, bigint] & { tokenAAmount: bigint; tokenBAmount: bigint }],
    "view"
  >;
  getFunction(
    nameOrSignature: "getLiquidityValueAfterArbitrageToPrice"
  ): TypedContractMethod<
    [
      tokenA: AddressLike,
      tokenB: AddressLike,
      truePriceTokenA: BigNumberish,
      truePriceTokenB: BigNumberish,
      liquidityAmount: BigNumberish
    ],
    [[bigint, bigint] & { tokenAAmount: bigint; tokenBAmount: bigint }],
    "view"
  >;
  getFunction(
    nameOrSignature: "getReservesAfterArbitrage"
  ): TypedContractMethod<
    [
      tokenA: AddressLike,
      tokenB: AddressLike,
      truePriceTokenA: BigNumberish,
      truePriceTokenB: BigNumberish
    ],
    [[bigint, bigint] & { reserveA: bigint; reserveB: bigint }],
    "view"
  >;

  filters: {};
}
