/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumberish,
  BytesLike,
  FunctionFragment,
  Result,
  Interface,
  AddressLike,
  ContractRunner,
  ContractMethod,
  Listener,
} from "ethers";
import type {
  TypedContractEvent,
  TypedDeferredTopicFilter,
  TypedEventLog,
  TypedListener,
  TypedContractMethod,
} from "../../../common";

export interface IUniswapV2LockerInterface extends Interface {
  getFunction(nameOrSignature: "lockLPToken"): FunctionFragment;

  encodeFunctionData(
    functionFragment: "lockLPToken",
    values: [
      AddressLike,
      BigNumberish,
      BigNumberish,
      AddressLike,
      boolean,
      AddressLike
    ]
  ): string;

  decodeFunctionResult(
    functionFragment: "lockLPToken",
    data: BytesLike
  ): Result;
}

export interface IUniswapV2Locker extends BaseContract {
  connect(runner?: ContractRunner | null): IUniswapV2Locker;
  waitForDeployment(): Promise<this>;

  interface: IUniswapV2LockerInterface;

  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  on<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  once<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  once<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>;
  removeAllListeners<TCEvent extends TypedContractEvent>(
    event?: TCEvent
  ): Promise<this>;

  lockLPToken: TypedContractMethod<
    [
      _lpToken: AddressLike,
      _amount: BigNumberish,
      _unlock_date: BigNumberish,
      _referral: AddressLike,
      _fee_in_eth: boolean,
      _withdrawer: AddressLike
    ],
    [void],
    "payable"
  >;

  getFunction<T extends ContractMethod = ContractMethod>(
    key: string | FunctionFragment
  ): T;

  getFunction(
    nameOrSignature: "lockLPToken"
  ): TypedContractMethod<
    [
      _lpToken: AddressLike,
      _amount: BigNumberish,
      _unlock_date: BigNumberish,
      _referral: AddressLike,
      _fee_in_eth: boolean,
      _withdrawer: AddressLike
    ],
    [void],
    "payable"
  >;

  filters: {};
}
