/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import { Contract, Interface, type ContractRunner } from "ethers";
import type {
  IMemeWhitelist,
  IMemeWhitelistInterface,
} from "../../../../contracts/memoo/interfaces/IMemeWhitelist";

const _abi = [
  {
    inputs: [
      {
        internalType: "bytes",
        name: "message",
        type: "bytes",
      },
      {
        internalType: "bytes",
        name: "signature",
        type: "bytes",
      },
    ],
    name: "verify",
    outputs: [
      {
        components: [
          {
            internalType: "address",
            name: "token",
            type: "address",
          },
          {
            internalType: "address",
            name: "user",
            type: "address",
          },
          {
            internalType: "uint256",
            name: "count",
            type: "uint256",
          },
          {
            internalType: "uint256",
            name: "timestamp",
            type: "uint256",
          },
        ],
        internalType: "struct IMemeWhitelist.WhitelistMessage",
        name: "",
        type: "tuple",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
] as const;

export class IMemeWhitelist__factory {
  static readonly abi = _abi;
  static createInterface(): IMemeWhitelistInterface {
    return new Interface(_abi) as IMemeWhitelistInterface;
  }
  static connect(
    address: string,
    runner?: ContractRunner | null
  ): IMemeWhitelist {
    return new Contract(address, _abi, runner) as unknown as IMemeWhitelist;
  }
}
