/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import { Contract, Interface, type ContractRunner } from "ethers";
import type {
  IMemeFactory,
  IMemeFactoryInterface,
} from "../../../../contracts/memoo/interfaces/IMemeFactory";

const _abi = [
  {
    anonymous: false,
    inputs: [
      {
        indexed: false,
        internalType: "address",
        name: "meme",
        type: "address",
      },
      {
        components: [
          {
            components: [
              {
                internalType: "address",
                name: "creator",
                type: "address",
              },
              {
                internalType: "address",
                name: "defaultAdmin",
                type: "address",
              },
              {
                internalType: "address",
                name: "pauser",
                type: "address",
              },
              {
                internalType: "address",
                name: "minter",
                type: "address",
              },
              {
                internalType: "string",
                name: "name",
                type: "string",
              },
              {
                internalType: "string",
                name: "symbol",
                type: "string",
              },
              {
                internalType: "uint256",
                name: "totalSupply",
                type: "uint256",
              },
              {
                internalType: "uint8",
                name: "decimals",
                type: "uint8",
              },
              {
                internalType: "address",
                name: "payToken",
                type: "address",
              },
              {
                internalType: "uint256",
                name: "idoPrice",
                type: "uint256",
              },
              {
                internalType: "uint256",
                name: "airdropPrice",
                type: "uint256",
              },
              {
                internalType: "uint256",
                name: "preLaunchSecond",
                type: "uint256",
              },
              {
                internalType: "uint256",
                name: "idoUserBuyLimit",
                type: "uint256",
              },
            ],
            internalType: "struct MemeInfoStructs.MemeInfo",
            name: "memeInfo",
            type: "tuple",
          },
          {
            components: [
              {
                internalType: "address",
                name: "memeFactory",
                type: "address",
              },
              {
                internalType: "address",
                name: "treasury",
                type: "address",
              },
              {
                internalType: "address",
                name: "memeWhitelist",
                type: "address",
              },
              {
                internalType: "address",
                name: "uniswapV2Factory",
                type: "address",
              },
              {
                internalType: "address",
                name: "uniswapV2Router02",
                type: "address",
              },
              {
                internalType: "uint256",
                name: "uniswapDeadline",
                type: "uint256",
              },
              {
                internalType: "address",
                name: "liquidityHolder",
                type: "address",
              },
              {
                internalType: "address",
                name: "liquidityLocker",
                type: "address",
              },
              {
                internalType: "address",
                name: "platformMemeRecipient",
                type: "address",
              },
              {
                internalType: "address payable",
                name: "platformFeeRecipient",
                type: "address",
              },
              {
                internalType: "uint256",
                name: "platformFeeRateIdo",
                type: "uint256",
              },
              {
                internalType: "uint256",
                name: "platformFeeRateDenominatorIdo",
                type: "uint256",
              },
              {
                internalType: "uint256",
                name: "platformFeeCreateMeme",
                type: "uint256",
              },
              {
                internalType: "address",
                name: "platformFeeCreateMemePayToken",
                type: "address",
              },
              {
                internalType: "uint256",
                name: "idoCreatorBuyLimit",
                type: "uint256",
              },
              {
                components: [
                  {
                    internalType: "uint256",
                    name: "creator",
                    type: "uint256",
                  },
                  {
                    internalType: "uint256",
                    name: "ido",
                    type: "uint256",
                  },
                  {
                    internalType: "uint256",
                    name: "lp",
                    type: "uint256",
                  },
                  {
                    internalType: "uint256",
                    name: "airdrop",
                    type: "uint256",
                  },
                  {
                    internalType: "uint256",
                    name: "platform",
                    type: "uint256",
                  },
                ],
                internalType: "struct MemooManageStructs.TokenAllocation",
                name: "allocation",
                type: "tuple",
              },
            ],
            internalType: "struct MemooManageStructs.MemooConfig",
            name: "memooConfig",
            type: "tuple",
          },
          {
            internalType: "uint256",
            name: "creatorTotal",
            type: "uint256",
          },
          {
            internalType: "uint256",
            name: "platformTotal",
            type: "uint256",
          },
          {
            internalType: "uint256",
            name: "memeCreateTimestamp",
            type: "uint256",
          },
        ],
        indexed: false,
        internalType: "struct MemeInfoStructs.MemeConfigInfo",
        name: "memeConfigInfo",
        type: "tuple",
      },
    ],
    name: "MemeCreated",
    type: "event",
  },
  {
    inputs: [
      {
        components: [
          {
            internalType: "address",
            name: "creator",
            type: "address",
          },
          {
            internalType: "address",
            name: "defaultAdmin",
            type: "address",
          },
          {
            internalType: "address",
            name: "pauser",
            type: "address",
          },
          {
            internalType: "address",
            name: "minter",
            type: "address",
          },
          {
            internalType: "string",
            name: "name",
            type: "string",
          },
          {
            internalType: "string",
            name: "symbol",
            type: "string",
          },
          {
            internalType: "uint256",
            name: "totalSupply",
            type: "uint256",
          },
          {
            internalType: "uint8",
            name: "decimals",
            type: "uint8",
          },
          {
            internalType: "address",
            name: "payToken",
            type: "address",
          },
          {
            internalType: "uint256",
            name: "idoPrice",
            type: "uint256",
          },
          {
            internalType: "uint256",
            name: "airdropPrice",
            type: "uint256",
          },
          {
            internalType: "uint256",
            name: "preLaunchSecond",
            type: "uint256",
          },
          {
            internalType: "uint256",
            name: "idoUserBuyLimit",
            type: "uint256",
          },
        ],
        internalType: "struct MemeInfoStructs.MemeInfo",
        name: "memeInfo",
        type: "tuple",
      },
      {
        components: [
          {
            internalType: "address",
            name: "memeFactory",
            type: "address",
          },
          {
            internalType: "address",
            name: "treasury",
            type: "address",
          },
          {
            internalType: "address",
            name: "memeWhitelist",
            type: "address",
          },
          {
            internalType: "address",
            name: "uniswapV2Factory",
            type: "address",
          },
          {
            internalType: "address",
            name: "uniswapV2Router02",
            type: "address",
          },
          {
            internalType: "uint256",
            name: "uniswapDeadline",
            type: "uint256",
          },
          {
            internalType: "address",
            name: "liquidityHolder",
            type: "address",
          },
          {
            internalType: "address",
            name: "liquidityLocker",
            type: "address",
          },
          {
            internalType: "address",
            name: "platformMemeRecipient",
            type: "address",
          },
          {
            internalType: "address payable",
            name: "platformFeeRecipient",
            type: "address",
          },
          {
            internalType: "uint256",
            name: "platformFeeRateIdo",
            type: "uint256",
          },
          {
            internalType: "uint256",
            name: "platformFeeRateDenominatorIdo",
            type: "uint256",
          },
          {
            internalType: "uint256",
            name: "platformFeeCreateMeme",
            type: "uint256",
          },
          {
            internalType: "address",
            name: "platformFeeCreateMemePayToken",
            type: "address",
          },
          {
            internalType: "uint256",
            name: "idoCreatorBuyLimit",
            type: "uint256",
          },
          {
            components: [
              {
                internalType: "uint256",
                name: "creator",
                type: "uint256",
              },
              {
                internalType: "uint256",
                name: "ido",
                type: "uint256",
              },
              {
                internalType: "uint256",
                name: "lp",
                type: "uint256",
              },
              {
                internalType: "uint256",
                name: "airdrop",
                type: "uint256",
              },
              {
                internalType: "uint256",
                name: "platform",
                type: "uint256",
              },
            ],
            internalType: "struct MemooManageStructs.TokenAllocation",
            name: "allocation",
            type: "tuple",
          },
        ],
        internalType: "struct MemooManageStructs.MemooConfig",
        name: "memooConfig",
        type: "tuple",
      },
    ],
    name: "createMeme",
    outputs: [
      {
        internalType: "address",
        name: "meme",
        type: "address",
      },
      {
        components: [
          {
            components: [
              {
                internalType: "address",
                name: "creator",
                type: "address",
              },
              {
                internalType: "address",
                name: "defaultAdmin",
                type: "address",
              },
              {
                internalType: "address",
                name: "pauser",
                type: "address",
              },
              {
                internalType: "address",
                name: "minter",
                type: "address",
              },
              {
                internalType: "string",
                name: "name",
                type: "string",
              },
              {
                internalType: "string",
                name: "symbol",
                type: "string",
              },
              {
                internalType: "uint256",
                name: "totalSupply",
                type: "uint256",
              },
              {
                internalType: "uint8",
                name: "decimals",
                type: "uint8",
              },
              {
                internalType: "address",
                name: "payToken",
                type: "address",
              },
              {
                internalType: "uint256",
                name: "idoPrice",
                type: "uint256",
              },
              {
                internalType: "uint256",
                name: "airdropPrice",
                type: "uint256",
              },
              {
                internalType: "uint256",
                name: "preLaunchSecond",
                type: "uint256",
              },
              {
                internalType: "uint256",
                name: "idoUserBuyLimit",
                type: "uint256",
              },
            ],
            internalType: "struct MemeInfoStructs.MemeInfo",
            name: "memeInfo",
            type: "tuple",
          },
          {
            components: [
              {
                internalType: "address",
                name: "memeFactory",
                type: "address",
              },
              {
                internalType: "address",
                name: "treasury",
                type: "address",
              },
              {
                internalType: "address",
                name: "memeWhitelist",
                type: "address",
              },
              {
                internalType: "address",
                name: "uniswapV2Factory",
                type: "address",
              },
              {
                internalType: "address",
                name: "uniswapV2Router02",
                type: "address",
              },
              {
                internalType: "uint256",
                name: "uniswapDeadline",
                type: "uint256",
              },
              {
                internalType: "address",
                name: "liquidityHolder",
                type: "address",
              },
              {
                internalType: "address",
                name: "liquidityLocker",
                type: "address",
              },
              {
                internalType: "address",
                name: "platformMemeRecipient",
                type: "address",
              },
              {
                internalType: "address payable",
                name: "platformFeeRecipient",
                type: "address",
              },
              {
                internalType: "uint256",
                name: "platformFeeRateIdo",
                type: "uint256",
              },
              {
                internalType: "uint256",
                name: "platformFeeRateDenominatorIdo",
                type: "uint256",
              },
              {
                internalType: "uint256",
                name: "platformFeeCreateMeme",
                type: "uint256",
              },
              {
                internalType: "address",
                name: "platformFeeCreateMemePayToken",
                type: "address",
              },
              {
                internalType: "uint256",
                name: "idoCreatorBuyLimit",
                type: "uint256",
              },
              {
                components: [
                  {
                    internalType: "uint256",
                    name: "creator",
                    type: "uint256",
                  },
                  {
                    internalType: "uint256",
                    name: "ido",
                    type: "uint256",
                  },
                  {
                    internalType: "uint256",
                    name: "lp",
                    type: "uint256",
                  },
                  {
                    internalType: "uint256",
                    name: "airdrop",
                    type: "uint256",
                  },
                  {
                    internalType: "uint256",
                    name: "platform",
                    type: "uint256",
                  },
                ],
                internalType: "struct MemooManageStructs.TokenAllocation",
                name: "allocation",
                type: "tuple",
              },
            ],
            internalType: "struct MemooManageStructs.MemooConfig",
            name: "memooConfig",
            type: "tuple",
          },
          {
            internalType: "uint256",
            name: "creatorTotal",
            type: "uint256",
          },
          {
            internalType: "uint256",
            name: "platformTotal",
            type: "uint256",
          },
          {
            internalType: "uint256",
            name: "memeCreateTimestamp",
            type: "uint256",
          },
        ],
        internalType: "struct MemeInfoStructs.MemeConfigInfo",
        name: "memeConfigInfo",
        type: "tuple",
      },
    ],
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    inputs: [
      {
        internalType: "address",
        name: "meme",
        type: "address",
      },
    ],
    name: "memeConfigInfo",
    outputs: [
      {
        components: [
          {
            components: [
              {
                internalType: "address",
                name: "creator",
                type: "address",
              },
              {
                internalType: "address",
                name: "defaultAdmin",
                type: "address",
              },
              {
                internalType: "address",
                name: "pauser",
                type: "address",
              },
              {
                internalType: "address",
                name: "minter",
                type: "address",
              },
              {
                internalType: "string",
                name: "name",
                type: "string",
              },
              {
                internalType: "string",
                name: "symbol",
                type: "string",
              },
              {
                internalType: "uint256",
                name: "totalSupply",
                type: "uint256",
              },
              {
                internalType: "uint8",
                name: "decimals",
                type: "uint8",
              },
              {
                internalType: "address",
                name: "payToken",
                type: "address",
              },
              {
                internalType: "uint256",
                name: "idoPrice",
                type: "uint256",
              },
              {
                internalType: "uint256",
                name: "airdropPrice",
                type: "uint256",
              },
              {
                internalType: "uint256",
                name: "preLaunchSecond",
                type: "uint256",
              },
              {
                internalType: "uint256",
                name: "idoUserBuyLimit",
                type: "uint256",
              },
            ],
            internalType: "struct MemeInfoStructs.MemeInfo",
            name: "memeInfo",
            type: "tuple",
          },
          {
            components: [
              {
                internalType: "address",
                name: "memeFactory",
                type: "address",
              },
              {
                internalType: "address",
                name: "treasury",
                type: "address",
              },
              {
                internalType: "address",
                name: "memeWhitelist",
                type: "address",
              },
              {
                internalType: "address",
                name: "uniswapV2Factory",
                type: "address",
              },
              {
                internalType: "address",
                name: "uniswapV2Router02",
                type: "address",
              },
              {
                internalType: "uint256",
                name: "uniswapDeadline",
                type: "uint256",
              },
              {
                internalType: "address",
                name: "liquidityHolder",
                type: "address",
              },
              {
                internalType: "address",
                name: "liquidityLocker",
                type: "address",
              },
              {
                internalType: "address",
                name: "platformMemeRecipient",
                type: "address",
              },
              {
                internalType: "address payable",
                name: "platformFeeRecipient",
                type: "address",
              },
              {
                internalType: "uint256",
                name: "platformFeeRateIdo",
                type: "uint256",
              },
              {
                internalType: "uint256",
                name: "platformFeeRateDenominatorIdo",
                type: "uint256",
              },
              {
                internalType: "uint256",
                name: "platformFeeCreateMeme",
                type: "uint256",
              },
              {
                internalType: "address",
                name: "platformFeeCreateMemePayToken",
                type: "address",
              },
              {
                internalType: "uint256",
                name: "idoCreatorBuyLimit",
                type: "uint256",
              },
              {
                components: [
                  {
                    internalType: "uint256",
                    name: "creator",
                    type: "uint256",
                  },
                  {
                    internalType: "uint256",
                    name: "ido",
                    type: "uint256",
                  },
                  {
                    internalType: "uint256",
                    name: "lp",
                    type: "uint256",
                  },
                  {
                    internalType: "uint256",
                    name: "airdrop",
                    type: "uint256",
                  },
                  {
                    internalType: "uint256",
                    name: "platform",
                    type: "uint256",
                  },
                ],
                internalType: "struct MemooManageStructs.TokenAllocation",
                name: "allocation",
                type: "tuple",
              },
            ],
            internalType: "struct MemooManageStructs.MemooConfig",
            name: "memooConfig",
            type: "tuple",
          },
          {
            internalType: "uint256",
            name: "creatorTotal",
            type: "uint256",
          },
          {
            internalType: "uint256",
            name: "platformTotal",
            type: "uint256",
          },
          {
            internalType: "uint256",
            name: "memeCreateTimestamp",
            type: "uint256",
          },
        ],
        internalType: "struct MemeInfoStructs.MemeConfigInfo",
        name: "",
        type: "tuple",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
] as const;

export class IMemeFactory__factory {
  static readonly abi = _abi;
  static createInterface(): IMemeFactoryInterface {
    return new Interface(_abi) as IMemeFactoryInterface;
  }
  static connect(
    address: string,
    runner?: ContractRunner | null
  ): IMemeFactory {
    return new Contract(address, _abi, runner) as unknown as IMemeFactory;
  }
}
