/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import { Contract, Interface, type ContractRunner } from "ethers";
import type {
  ICountryList,
  ICountryListInterface,
} from "../../../contracts/uniswap-v2-locker/ICountryList";

const _abi = [
  {
    inputs: [
      {
        internalType: "uint16",
        name: "_countryCode",
        type: "uint16",
      },
    ],
    name: "countryIsValid",
    outputs: [
      {
        internalType: "bool",
        name: "",
        type: "bool",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
] as const;

export class ICountryList__factory {
  static readonly abi = _abi;
  static createInterface(): ICountryListInterface {
    return new Interface(_abi) as ICountryListInterface;
  }
  static connect(
    address: string,
    runner?: ContractRunner | null
  ): ICountryList {
    return new Contract(address, _abi, runner) as unknown as ICountryList;
  }
}
