/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type * as excitedApeYatchClubSol from "./ExcitedApeYatchClub.sol";
export type { excitedApeYatchClubSol };
