name: Deploy
run-name: Deploy of ${{ github.ref_name }} to ${{github.event.inputs.domain}}

on:
  workflow_dispatch:
    inputs:
      domain:
        type: choice
        description: Target
        required: true
        options:
          - STAGING

env:
  AWS_REGION: ap-southeast-2

jobs:
  build-staging:
    if: ${{ github.event.inputs.domain == 'STAGING' }}
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}

      - name: Build (${{ github.event.inputs.domain }})
        run: |
          npm install -g pnpm
          pnpm install --no-frozen-lockfile
          pnpm run build

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ env.AWS_REGION }}

      - name: Deploy to S3 (${{ github.event.inputs.domain }})
        run: |
          aws s3 sync dist/ s3://memoo-app-staging/
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
